### ISSUE TITLE
Can't find favorites.sqlite3 db

### ISSUE THREAD

**Issue by abazzalo** [f0rk0ne/NSEarch-GUI#1]
Hi,

Thanks for this tool <3

As I see it, dbmodule.py is trying to retrieve some date from a db in the app's root directory called "favorites.sqlite3" 

> 
> File "/opt/NSEarch-GUI/libs/dbmodule.py", line 565, in __dbconnect
>     db = lite.connect(FAVDBNAME)
>          ^^^^^^^^^^^^^^^^^^^^^^^
> sqlite3.OperationalError: unable to open database file

Since favorites.sqlite3 db is not there the script just crashes.

Best,
Agus

**Comment by f0rk0ne** [comment]
Hi , Could you explain more detail the issue, please, try explain which steps you followed to obtain the error 

Thanks !

**Comment by abazzalo** [comment]
git clone https://github.com/f0rk0ne/NSEarch-GUI.git 
bash install.sh
./nsearch

Traceback (most recent call last):
  File "/opt/NSEarch-GUI/nsearch.py", line 17, in <module>
    console = console.Console()
              ^^^^^^^^^^^^^^^^^
  File "/opt/NSEarch-GUI/libs/console.py", line 60, in __init__
    self.get_favorites()
  File "/opt/NSEarch-GUI/libs/console.py", line 67, in get_favorites
    tmp = dbmodule.get_favorites()
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/NSEarch-GUI/libs/dbmodule.py", line 358, in get_favorites
    db, cursor = __dbconnect(True)
                 ^^^^^^^^^^^^^^^^^
  File "/opt/NSEarch-GUI/libs/dbmodule.py", line 565, in __dbconnect
    db = lite.connect(FAVDBNAME)
         ^^^^^^^^^^^^^^^^^^^^^^^
**sqlite3.OperationalError: unable to open database file**

**Comment by f0rk0ne** [comment]
Good Night, I were debugging the script, but the error not happened, What you described sounds like if dbmodule.check_db() function isn't working, this function creates favorites database when not exists , Could you post which OS are you using?, user privileges, and any aditional information maybe helps to simulate the environment to found the error.

Thanks

**Comment by abazzalo** [comment]
Night!,

You're definitely right!, it was a privilege issue when dbmodule.check_db() was called. My bad, sorry for any apologies!

Thanks to you, Best,
